type = "issue"
description = "Partenaires faisant partie d'un réseau de Catégorie 2 mais catégorisé incorrectement."
message = "Fait partie du réseau {3} mais catégorisé en {4}."
formula = '''
=LET(
  dbHeaders; ACStructures!$1:$1;
  dbRows;    ACStructures!$2:$1000;

  outputHeaders; { "ID du Contact" \ "Nom" \ "Appartient-il à un grand réseau ayant une habilitation nationale ?" \ "Catégorie du partenaire" };
  outputIndexes; BYCOL(outputHeaders; LAMBDA(colName; MATCH(colName; dbHeaders; 0)));

  typeCol;    INDEX(dbRows; 0; MATCH("Type de structure"; dbHeaders; 0));
  networkCol; INDEX(dbRows; 0; MATCH("Appartient-il à un grand réseau ayant une habilitation nationale ?"; dbHeaders; 0));
  categoryCol; INDEX(dbRows; 0; MATCH("Catégorie du partenaire"; dbHeaders; 0));

  outputRows; FILTER(
    CHOOSECOLS(dbRows; outputIndexes);
    ISNUMBER(FIND("1_Partenaire"; typeCol));
    (networkCol = "ANDES (Solidarité Alimentaire France)") + (networkCol = "Croix Rouge") + (networkCol = "Restos du Cœur") + (networkCol = "Secours Populaire") + (networkCol = "UGESS (Union des groupements des Epiceries Sociales et Solidaires)");
    categoryCol <> "Catégorie 2"
  );

  VSTACK(outputHeaders; outputRows)
)
'''
