type = "issue"
description = "Partenaires qui reçoivent des produits CNES de la BA mais ne sont pas de type épicerie sociale."
message = "Reçoit des produits CNES mais n'est pas une épicerie sociale."
formula = '''
=LET(
  dbHeaders; ACStructures!$1:$1;
  dbRows;    ACStructures!$2:$1000;

  outputHeaders; { "ID du Contact" \ "Nom" };
  outputIndexes; BYCOL(outputHeaders; LAMBDA(colName; MATCH(colName; dbHeaders; 0)));

  typeCol;  INDEX(dbRows; 0; MATCH("Type de structure"; dbHeaders; 0));
  cnesCol;  INDEX(dbRows; 0; MATCH("Le partenaire reçoit-il des produits CNES ?"; dbHeaders; 0));
  modesCol; INDEX(dbRows; 0; MATCH("Modes de distribution de l'aide alimentaire"; dbHeaders; 0));

  outputRows; FILTER(
    CHOOSECOLS(dbRows; outputIndexes);
    ISNUMBER(FIND("1_Partenaire"; typeCol));
    ISERR(FIND("Epicerie Sociale"; modesCol));
    cnesCol = "Oui de la BA"
  );

  VSTACK(outputHeaders; outputRows)
)
'''