type = "warning"
description = "Partenaires dont les dates de signature de convention sont incohérentes."
message = "Les dates de signature de convention sont incohérente. Initiale : {3, date, dd/mm/yyyy}. Dernière : {4, date, dd/mm/yyyy}"
formula = '''
=LET(
  dbHeaders; ACStructures!$1:$1;
  dbRows;    ACStructures!$2:$1000;

  outputHeaders; { "ID du Contact" \ "Nom" \ "Date de la signature initiale de la convention / du contrat" \ "Date de la dernière signature de la convention / du contrat" };
  outputIndexes; BYCOL(outputHeaders; LAMBDA(colName; MATCH(colName; dbHeaders; 0)));


  typeCol;  INDEX(dbRows; 0; MATCH("Type de structure"; dbHeaders; 0));
  firstCol; INDEX(dbRows; 0; MATCH("Date de la signature initiale de la convention / du contrat"; dbHeaders; 0));
  lastCol;  INDEX(dbRows; 0; MATCH("Date de la dernière signature de la convention / du contrat"; dbHeaders; 0));

  outputRows; FILTER(
    CHOOSECOLS(dbRows; outputIndexes);
    ISNUMBER(FIND("1_Partenaire"; typeCol));
    firstCol > lastCol
  );

  VSTACK(outputHeaders; outputRows)
)
'''
