type = "info"
description = ""
message = "Pas d'interlocuteur RHYSA renseigné."
formula = '''
=LET(
  dbHeaders; ACStructures!$1:$1;
  dbRows;    ACStructures!$2:$1000;

  outputHeaders; { "ID du Contact" \ "Nom" };
  outputIndexes; BYCOL(outputHeaders; LAMBDA(colName; MATCH(colName; dbHeaders; 0)));

  idCol;   INDEX(dbRows; 0; MATCH("ID du Contact"; dbHeaders; 0));
  typeCol; INDEX(dbRows; 0; MATCH("Type de structure"; dbHeaders; 0));

  blacklistedIds; IFERROR(
    FILTER(
      ACPersonnes_Structures!$C$2:$C;
      ISNUMBER(FIND("RHYSA"; ACPersonnes_Structures!$D$2:$D))
    );
    ""
  );

  outputRows; FILTER(
    CHOOSECOLS(dbRows; outputIndexes);
    ISNUMBER(FIND("1_Partenaire"; typeCol));
    ISNA(XMATCH(idCol; blacklistedIds))
  );

  VSTACK(outputHeaders; outputRows)
)
'''
