type = "warning"
description = "Partenaires qui souhaitent recevoir des produits frais mais n'ont ni réfrigérateurs ni chambres froides positives dans leur liste d'équipement."
message = "Souhaite recevoir du frais sans stockage réfrigéré."
formula = """
=LET(
  dbHeaders; ACStructures!$1:$1;
  dbRows;    ACStructures!$2:$1000;

  outputHeaders; { "ID du Contact" \ "Nom" };
  outputIndexes; BYCOL(outputHeaders; LAMBDA(colName; MATCH(colName; dbHeaders; 0)));

  typeCol;  INDEX(dbRows; 0; MATCH("Type de structure"; dbHeaders; 0));
  equipCol; INDEX(dbRows; 0; MATCH("Equipements/Locaux"; dbHeaders; 0));
  prodCol;  INDEX(dbRows; 0; MATCH("Produits de la BA souhaités par le partenaire"; dbHeaders; 0));

  outputRows; FILTER(
    CHOOSECOLS(dbRows; outputIndexes);
    ISNUMBER(FIND("1_Partenaire"; typeCol));
    ISNUMBER(FIND("Frais"; prodCol));
    NOT(REGEXMATCH("Chambre froide positive|Réfrigérateur"; equipCol))
  );

  VSTACK(outputHeaders; outputRows)
)
"""